import dynamic from 'next/dynamic';
import React from 'react';
import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
    return twMerge(clsx(inputs));
}

// Added 'getting-started' to the Category type
export type Category =
    | 'getting-started'
    | 'navbar'
    | 'hero'
    | 'infinite-scroller'
    | 'stats'
    | 'bento-grid'
    | 'background'
    | 'layout'
    | 'testimonial'
    | 'cta'
    | 'faq'
    | 'pricing'
    | 'footer'
    | 'button'
    | 'form'
    | 'blog'
    | 'sponsor'
    | 'parallax'
    | 'text'
    | 'styles';
export type Tag = 'new' | 'updated' | 'pro' | 'beta';

export interface ComponentEntry {
    id: string;
    name: string;
    description: string;
    category: Category;
    tags?: Tag[];
    component: React.ComponentType<any>;
    sourceCodePath: string;
    dependencies?: string[];
}

export const registry: ComponentEntry[] = [
    {
        id: 'introduction',
        name: 'Introduction',
        description: 'How to use Basebox and integrate components into your project.',
        category: 'getting-started',
        component: dynamic(() => Promise.resolve(() => null)),
        sourceCodePath: '',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'hero-1',
        name: 'hero-1',
        description: 'hero section text-button-image',
        category: 'hero',
        tags: ['new'],
        component: dynamic(() => import('@/components/Hero/hero-1').then(mod => mod.Hero)),
        sourceCodePath: 'components/Hero/hero-1.tsx',
        dependencies: ['framer-motion', 'lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'hero-2',
        name: 'hero-2',
        description: 'Clean centered typography with a large dashboard preview and feature grid.',
        category: 'hero',
        tags: ['new'],
        component: dynamic(() => import('@/components/Hero/hero-2').then(mod => mod.Hero)),
        sourceCodePath: 'components/Hero/hero-2.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'hero-3',
        name: 'hero-3',
        description: 'Modern scale hero with an infinite scroller logo cloud and background shading.',
        category: 'hero',
        tags: ['new'],
        component: dynamic(() => import('@/components/Hero/hero-3').then(mod => mod.Hero)),
        sourceCodePath: 'components/Hero/hero-3.tsx',
        dependencies: ['framer-motion', 'react-use-measure', 'lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'hero-4',
        name: 'hero-4',
        description: 'A breathtaking full-screen hero section with cinematic mountain backgrounds, serif typography, and a glass-morphism badge.',
        category: 'hero',
        tags: ['new', 'pro'],
        component: dynamic(() => import('@/components/Hero/hero-4').then(mod => mod.Hero)),
        sourceCodePath: 'components/Hero/hero-4.tsx',
        dependencies: ['framer-motion', 'lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'background-1',
        name: 'Aurora',
        description: 'Animated WebGL Aurora background with customizable color stops and speed.',
        category: 'background',
        tags: ['new'],
        component: dynamic(() => import('@/components/Background/background-1').then(mod => mod.Background)),
        sourceCodePath: 'components/Background/background-1.tsx',
        dependencies: ['ogl', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'background-2',
        name: 'Granient',
        description: 'Grainy mesh gradient with complex warp distortion and animated noise.',
        category: 'background',
        tags: ['new'],
        component: dynamic(() => import('@/components/Background/background-2').then(mod => mod.Background)),
        sourceCodePath: 'components/Background/background-2.tsx',
        dependencies: ['ogl', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'background-3',
        name: 'Silk',
        description: 'A smooth, wavy silk-textured shader with customizable noise and rotation.',
        category: 'background',
        tags: ['new'],
        component: dynamic(() => import('@/components/Background/background-3').then(mod => mod.Background)),
        sourceCodePath: 'components/Background/background-3.tsx',
        dependencies: ['three', '@react-three/fiber', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'background-4',
        name: 'Dots',
        description: 'Interactive dot grid with physics-based mouse interactions and shockwave clicks.',
        category: 'background',
        tags: ['new'],
        component: dynamic(() => import('@/components/Background/background-4').then(mod => mod.Background)),
        sourceCodePath: 'components/Background/background-4.tsx',
        dependencies: ['gsap', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'background-5',
        name: 'Particles',
        description: 'Interactive particle animation that reacts to mouse movement.',
        category: 'background',
        tags: ['new'],
        component: dynamic(() => import('@/components/Background/background-5').then(mod => mod.Background)),
        sourceCodePath: 'components/Background/background-5.tsx',
        dependencies: ['clsx', 'tailwind-merge', 'next-themes'],
    },
    {
        id: 'background-6',
        name: 'Dot Pattern',
        description: 'An interactive svg dot pattern backend with glowing animations.',
        category: 'background',
        tags: ['new'],
        component: dynamic(() => import('@/components/Background/background-6').then(mod => mod.Background)),
        sourceCodePath: 'components/Background/background-6.tsx',
        dependencies: ['framer-motion', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'infinite-scroller',
        name: 'Infinite Scroller',
        description: 'A seamless, high-performance horizontal auto-scroller for logos and brands.',
        category: 'infinite-scroller',
        tags: ['new'],
        component: dynamic(() => import('@/components/Scroller/infinite-scroller').then(mod => mod.InfiniteScroller)),
        sourceCodePath: 'components/Scroller/infinite-scroller.tsx',
        dependencies: ['framer-motion', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'infinite-scroller-2',
        name: 'Infinite Scroller 2',
        description: 'Brand logo trusted scroller using framer-motion.',
        category: 'infinite-scroller',
        tags: ['new'],
        component: dynamic(() => import('@/components/Scroller/infinite-scroller-2').then(mod => mod.InfiniteScroller2)),
        sourceCodePath: 'components/Scroller/infinite-scroller-2.tsx',
        dependencies: ['framer-motion', 'react-use-measure', 'lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: '2b-2s',
        name: '2b-2s',
        description: 'Bento grid with 2 large feature cards and 2 small horizontal highlight cards.',
        category: 'bento-grid',
        tags: ['new'],
        component: dynamic(() => import('@/components/Bento-grid/2b-2s').then(mod => mod.BentoGrid)),
        sourceCodePath: 'components/Bento-grid/2b-2s.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: '1b-1m-2s',
        name: '1b-1m-2s',
        description: 'Bento grid featuring a large main card, two square cards, and a wide medium card.',
        category: 'bento-grid',
        tags: ['new'],
        component: dynamic(() => import('@/components/Bento-grid/1b-1m-2s').then(mod => mod.BentoGrid)),
        sourceCodePath: 'components/Bento-grid/1b-1m-2s.tsx',
        dependencies: ['framer-motion', 'lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: '1m-4s',
        name: '1m-4s',
        description: 'A high-impact bento layout featuring one central tall card flanked by four supporting small cards.',
        category: 'bento-grid',
        tags: ['new'],
        component: dynamic(() => import('@/components/Bento-grid/1m-4s').then(mod => mod.BentoGrid)),
        sourceCodePath: 'components/Bento-grid/1m-4s.tsx',
        dependencies: ['clsx', 'tailwind-merge'],
    },
    {
        id: '1b-2s',
        name: '1b-2s',
        description: 'Bento layout with one large featured card and two smaller stacked cards, optimized for blog or portfolio previews.',
        category: 'bento-grid',
        tags: ['new'],
        component: dynamic(() => import('@/components/Bento-grid/1b-2s').then(mod => mod.BentoGrid)),
        sourceCodePath: 'components/Bento-grid/1b-2s.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: '2m-2s',
        name: '2m-2s',
        description: 'A balanced bento grid with 2 square cards and 2 larger rectangular cards (one vertical, one horizontal).',
        category: 'bento-grid',
        tags: ['new'],
        component: dynamic(() => import('@/components/Bento-grid/2m-2s').then(mod => mod.BentoGrid)),
        sourceCodePath: 'components/Bento-grid/2m-2s.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: '2m-3s',
        name: '2m-3s',
        description: 'Bento grid layout with 2 medium cards on top and 3 smaller cards on the bottom row.',
        category: 'bento-grid',
        tags: ['new'],
        component: dynamic(() => import('@/components/Bento-grid/2m-3s').then(mod => mod.BentoGrid)),
        sourceCodePath: 'components/Bento-grid/2m-3s.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'big-image-text',
        name: 'Big Image & Text',
        description: 'Large visual section with descriptive text and quotes (Visual Left).',
        category: 'layout',
        tags: ['new'],
        component: dynamic(() => import('@/components/Layout/big-image-text').then(mod => mod.BigImageText)),
        sourceCodePath: 'components/Layout/big-image-text.tsx',
        dependencies: ['clsx', 'tailwind-merge'],
    },
    {
        id: 'plus-points',
        name: 'Plus Points',
        description: 'A layout feature section that displays multiple feature points with checkmarks.',
        category: 'layout',
        tags: ['new'],
        component: dynamic(() => import('@/components/Layout/plus-points').then(mod => mod.PlusPoints)),
        sourceCodePath: 'components/Layout/plus-points.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'plus-points-2',
        name: 'Enterprise Feature Row',
        description: 'A premium horizontal layout section featuring a cinematic heading and organized metric points.',
        category: 'layout',
        tags: ['new'],
        component: dynamic(() => import('@/components/Layout/plus-points-2').then(mod => mod.PlusPoints2)),
        sourceCodePath: 'components/Layout/plus-points-2.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge', 'framer-motion'],
    },
    {
        id: 'feature-hover',
        name: 'Feature Hover',
        description: 'A grid of features with sleek hover effects and glowing gradients.',
        category: 'layout',
        tags: ['new'],
        component: dynamic(() => import('@/components/Layout/feature-hover').then(mod => mod.FeatureHover)),
        sourceCodePath: 'components/Layout/feature-hover.tsx',
        dependencies: ['framer-motion', 'lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'big-text-image',
        name: 'Big Text & Image',
        description: 'Large visual section with descriptive text and quotes (Visual Right).',
        category: 'layout',
        tags: ['new'],
        component: dynamic(() => import('@/components/Layout/big-text-image').then(mod => mod.BigTextImage)),
        sourceCodePath: 'components/Layout/big-text-image.tsx',
        dependencies: ['clsx', 'tailwind-merge'],
    },
    {
        id: 'medium-image-text',
        name: 'Medium Image & Text',
        description: 'A balanced grid layout with a medium-scale visual on the left and right-aligned typography.',
        category: 'layout',
        tags: ['new'],
        component: dynamic(() => import('@/components/Layout/Medium-image-text').then(mod => mod.MediumImageText)),
        sourceCodePath: 'components/Layout/Medium-image-text.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'medium-text-image',
        name: 'Medium Text & Image',
        description: 'A classic mirrored grid layout with bold left-aligned text and a supporting visual on the right.',
        category: 'layout',
        tags: ['new'],
        component: dynamic(() => import('@/components/Layout/Medium-text-image').then(mod => mod.MediumTextImage)),
        sourceCodePath: 'components/Layout/Medium-text-image.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'image-selector-1',
        name: 'Image Selector 1',
        description: 'An interactive layout where selecting text-based feature cards updates a central visual display with smooth motion transitions.',
        category: 'layout',
        tags: ['new'],
        component: dynamic(() => import('@/components/Layout/image-selector-1').then(mod => mod.ImageSelector1)),
        sourceCodePath: 'components/Layout/image-selector-1.tsx',
        dependencies: ['framer-motion', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'image-selector-2',
        name: 'Image Selector 2',
        description: 'An accordion-style feature selector that reveals content and updates a primary visual in real-time.',
        category: 'layout',
        tags: ['new'],
        component: dynamic(() => import('@/components/Layout/image-selector-2').then(mod => mod.ImageSelector2)),
        sourceCodePath: 'components/Layout/image-selector-2.tsx',
        dependencies: ['framer-motion', 'lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'automatic-image',
        name: 'Automatic Image',
        description: 'An autoplaying feature showcase with synchronized progress bars and animated visual transitions.',
        category: 'layout',
        tags: ['new'],
        component: dynamic(() => import('@/components/Layout/automatic-image').then(mod => mod.AutomaticImage)),
        sourceCodePath: 'components/Layout/automatic-image.tsx',
        dependencies: ['framer-motion', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'image-slider-1',
        name: 'Image Slider 1',
        description: 'A horizontal scrolling showcase with glassmorphism overlays for deep-dive product details.',
        category: 'layout',
        tags: ['new'],
        component: dynamic(() => import('@/components/Layout/image-slider-1').then(mod => mod.ImageSlider1)),
        sourceCodePath: 'components/Layout/image-slider-1.tsx',
        dependencies: ['framer-motion', 'lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'image-slider-2',
        name: 'Image Slider 2',
        description: 'An alternating carousel layout that mixes text-based testimonials with visual brand imagery.',
        category: 'layout',
        tags: ['new'],
        component: dynamic(() => import('@/components/Layout/image-slider-2').then(mod => mod.ImageSlider2)),
        sourceCodePath: 'components/Layout/image-slider-2.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'text-images-1',
        name: 'Interactive Image Grid',
        description: 'A premium grid of cards that animate between images and reveal descriptions on hover.',
        category: 'layout',
        tags: ['new'],
        component: dynamic(() => import('@/components/Layout/text-images-1').then(mod => mod.TextImages1)),
        sourceCodePath: 'components/Layout/text-images-1.tsx',
        dependencies: ['framer-motion', 'lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'testimonial-horizontal-slider',
        name: 'Horizontal Slider',
        description: 'A seamless, dual-row horizontal scrolling marquee for highlighting user feedback and reviews.',
        category: 'testimonial',
        tags: ['new'],
        component: dynamic(() => import('@/components/Testimonial/testimonial-horizontal-slider').then(mod => mod.TestimonialSlider)),
        sourceCodePath: 'components/Testimonial/testimonial-horizontal-slider.tsx',
        dependencies: ['framer-motion', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'testimonial-vertical-slider',
        name: 'Vertical Slider',
        description: 'An infinite vertical auto-scrolling testimonial grid with three-column density.',
        category: 'testimonial',
        tags: ['new'],
        component: dynamic(() => import('@/components/Testimonial/testimonial-vertical-slider').then(mod => mod.Testimonial)),
        sourceCodePath: 'components/Testimonial/testimonial-vertical-slider.tsx',
        dependencies: ['framer-motion', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'cta-card-1',
        name: 'CTA Card 1',
        description: 'A high-contrast horizontal call-to-action card with glassmorphism overlays and responsive button layouts.',
        category: 'cta',
        tags: ['new'],
        component: dynamic(() => import('@/components/CTA/cta-card-1').then(mod => mod.CtaCard1)),
        sourceCodePath: 'components/CTA/cta-card-1.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'cta-card-2',
        name: 'Orbiting CTA',
        description: 'A futuristic CTA section featuring rotating orbital icons and Unsplash fallbacks mapping to the Basebox design system.',
        category: 'cta',
        tags: ['new'],
        component: dynamic(() => import('@/components/CTA/cta-card-2').then(mod => mod.CtaCard2)),
        sourceCodePath: 'components/CTA/cta-card-2.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'cta-card-3',
        name: 'Floating Icons CTA',
        description: 'An interactive hero section with floating lucide icons that react to mouse hover using framer physics.',
        category: 'cta',
        tags: ['new'],
        component: dynamic(() => import('@/components/CTA/cta-card-3').then(mod => mod.CtaCard3)),
        sourceCodePath: 'components/CTA/cta-card-3.tsx',
        dependencies: ['framer-motion', 'lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'faq-1',
        name: 'FAQ 1',
        description: 'A minimalist interactive accordion with numbered labels, hover animations, and spring-physics transitions.',
        category: 'faq',
        tags: ['new'],
        component: dynamic(() => import('@/components/FAQ/faq-1').then(mod => mod.Faq)),
        sourceCodePath: 'components/FAQ/faq-1.tsx',
        dependencies: ['framer-motion', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'faq-2',
        name: 'FAQ 2',
        description: 'A two-column FAQ section featuring a sticky header and interactive card-based accordions.',
        category: 'faq',
        tags: ['new'],
        component: dynamic(() => import('@/components/FAQ/faq-2').then(mod => mod.Faq)),
        sourceCodePath: 'components/FAQ/faq-2.tsx',
        dependencies: ['lucide-react', 'framer-motion', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'faq-3',
        name: 'FAQ 3',
        description: 'A glowing FAQ accordion component with spring layout animations and outline cards.',
        category: 'faq',
        tags: ['new'],
        component: dynamic(() => import('@/components/FAQ/faq-3').then(mod => mod.Faq3)),
        sourceCodePath: 'components/FAQ/faq-3.tsx',
        dependencies: ['lucide-react', 'framer-motion', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'faq-4',
        name: 'FAQ 4',
        description: 'A traditional Shadcn-based accordion featuring raw Radix primitives and Tailwind animation variables.',
        category: 'faq',
        tags: ['new'],
        component: dynamic(() => import('@/components/FAQ/faq-4').then(mod => mod.Faq4)),
        sourceCodePath: 'components/FAQ/faq-4.tsx',
        dependencies: ['lucide-react', '@radix-ui/react-accordion', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'faq-5',
        name: 'FAQ 5',
        description: 'A large typography-focused FAQ component leveraging accordion compression styles for a minimal editorial feel.',
        category: 'faq',
        tags: ['new'],
        component: dynamic(() => import('@/components/FAQ/faq-5').then(mod => mod.Faq5)),
        sourceCodePath: 'components/FAQ/faq-5.tsx',
        dependencies: ['lucide-react', '@radix-ui/react-accordion', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'pricing-1',
        name: 'Standard Pricing',
        description: 'A responsive three-column pricing section with a monthly/yearly toggle and featured plan highlighting.',
        category: 'pricing',
        tags: ['new'],
        component: dynamic(() => import('@/components/Pricing/price-1').then(mod => mod.Pricing)),
        sourceCodePath: 'components/Pricing/price-1.tsx',
        dependencies: ['framer-motion', 'lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'price-2',
        name: 'Pricing Upgrade',
        description: 'A focused pricing upgrade section featuring a split layout with a visual showcase and a detailed feature list.',
        category: 'pricing',
        tags: ['new'],
        component: dynamic(() => import('@/components/Pricing/price-2').then(mod => mod.PricingUpgrade)),
        sourceCodePath: 'components/Pricing/price-2.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'price-3',
        name: 'Pricing Premium',
        description: 'Elite subscription card with an interactive billing toggle and premium feature list.',
        category: 'pricing',
        tags: ['new'],
        component: dynamic(() => import('@/components/Pricing/price-3').then(mod => mod.PricingPremium)),
        sourceCodePath: 'components/Pricing/price-3.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'footer-1',
        name: 'Oversized Brand Footer',
        description: 'A modern footer featuring high-contrast typography, large brand lettering, and organized navigation columns.',
        category: 'footer',
        tags: ['new'],
        component: dynamic(() => import('@/components/Footer/footer-1').then(mod => mod.Footer)),
        sourceCodePath: 'components/Footer/footer-1.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'footer-2',
        name: 'Classic Column Footer',
        description: 'A traditional organized footer with column-based navigation, brand description, and social icon integration.',
        category: 'footer',
        tags: ['new'],
        component: dynamic(() => import('@/components/Footer/footer-2').then(mod => mod.Footer)),
        sourceCodePath: 'components/Footer/footer-2.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'footer-3',
        name: 'Neo-Minimalist Footer',
        description: 'A tech-focused footer with a newsletter input, grid background pattern, and interactive link animations.',
        category: 'footer',
        tags: ['new'],
        component: dynamic(() => import('@/components/Footer/footer-3').then(mod => mod.Footer3)),
        sourceCodePath: 'components/Footer/footer-3.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'glass-buttons',
        name: 'Glassmorphism Buttons',
        description: '3D interactive icon buttons featuring glassmorphism effects, depth transforms, and vibrant color gradients.',
        category: 'button',
        tags: ['new'],
        component: dynamic(() => import('@/components/Button/glass-buttons').then(mod => mod.GlassButtons)),
        sourceCodePath: 'components/Button/glass-buttons.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'social-buttons',
        name: 'Social Auth Buttons',
        description: 'A vertical stack of standardized social login buttons for Google, GitHub, and X (Twitter).',
        category: 'button',
        tags: ['new'],
        component: dynamic(() => import('@/components/Button/social-buttons').then(mod => mod.SocialButtons)),
        sourceCodePath: 'components/Button/social-buttons.tsx',
        dependencies: ['clsx', 'tailwind-merge'],
    },
    {
        id: 'button-showcase',
        name: 'Button Showcase',
        description: 'A comprehensive view of all button primitives, styles, and sizes available in the design system.',
        category: 'styles',
        tags: ['new'],
        component: dynamic(() => import('@/components/Style/button-showcase').then(mod => mod.ButtonShowcase)),
        sourceCodePath: 'components/Style/button-showcase.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'navbar-1',
        name: 'navbar-1',
        description: 'A responsive navbar that transforms from full-width to a floating pill on scroll.',
        category: 'navbar',
        tags: ['new'],
        component: dynamic(() => import('@/components/Navigation bar/navbar-1').then(mod => mod.Navbar)),
        sourceCodePath: 'components/Navigation bar/navbar-1.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'navbar-2',
        name: 'navbar-2',
        description: 'A tech-focused pill navbar that expands with spring physics to reveal detailed features.',
        category: 'navbar',
        tags: ['updated'],
        component: dynamic(() => import('@/components/Navigation bar/navbar-2').then(mod => mod.ExpandableNavbar)),
        sourceCodePath: 'components/Navigation bar/navbar-2.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge', 'framer-motion'],
    },
    {
        id: 'navbar-3',
        name: 'navbar-3',
        description: 'Sunday-inspired minimalist pill navbar that smoothly expands into a feature-rich mega menu.',
        category: 'navbar',
        tags: ['new', 'pro'],
        component: dynamic(() => import('@/components/Navigation bar/navbar-3').then(mod => mod.Navbar3)),
        sourceCodePath: 'components/Navigation bar/navbar-3.tsx',
        dependencies: ['framer-motion', 'lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'navbar-4',
        name: 'navbar-4',
        description: 'A comprehensive MetaMask-inspired mega menu navbar with colorful feature cards and a secondary sidebar.',
        category: 'navbar',
        tags: ['new'],
        component: dynamic(() => import('@/components/Navigation bar/navbar-4').then(mod => mod.Navbar4)),
        sourceCodePath: 'components/Navigation bar/navbar-4.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge', 'framer-motion'],
    },
    {
        id: 'navbar-5',
        name: 'navbar-5',
        description: 'A fullscreen animated navigation overlay powered by GSAP CustomEase with ambient shapes.',
        category: 'navbar',
        tags: ['new'],
        component: dynamic(() => import('@/components/Navigation bar/navbar-5').then(mod => mod.Navbar5)),
        sourceCodePath: 'components/Navigation bar/navbar-5.tsx',
        dependencies: ['gsap', 'lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'navbar-6',
        name: 'navbar-6',
        description: 'A responsive Shadcn UI mega-menu adapted into Basebox mapping standards with mobile slide-in nav.',
        category: 'navbar',
        tags: ['new'],
        component: dynamic(() => import('@/components/Navigation bar/navbar-6').then(mod => mod.Navbar6)),
        sourceCodePath: 'components/Navigation bar/navbar-6.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge', '@radix-ui/react-navigation-menu'],
    },
    {
        id: 'navbar-7',
        name: 'navbar-7',
        description: 'Premium glass navbar with intelligent mega-menus, scroll effects, and immersive mobile navigation.',
        category: 'navbar',
        tags: ['new', 'pro'],
        component: dynamic(() => import('@/components/Navigation bar/navbar-7').then(mod => mod.Navbar7)),
        sourceCodePath: 'components/Navigation bar/navbar-7.tsx',
        dependencies: ['framer-motion', 'lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'typography-showcase',
        name: 'Typography Showcase',
        description: 'A detailed overview of the typography system, including headings, body text, and status labels.',
        category: 'styles',
        tags: ['new'],
        component: dynamic(() => import('@/components/Style/typography-showcase').then(mod => mod.TypographyShowcase)),
        sourceCodePath: 'components/Style/typography-showcase.tsx',
        dependencies: ['clsx', 'tailwind-merge'],
    },
    {
        id: 'card-showcase',
        name: 'Card Showcase',
        description: 'A showcase of all card variants and surface primitives available in the design system.',
        category: 'styles',
        tags: ['new'],
        component: dynamic(() => import('@/components/Style/card-showcase').then(mod => mod.CardShowcase)),
        sourceCodePath: 'components/Style/card-showcase.tsx',
        dependencies: ['clsx', 'tailwind-merge'],
    },
    {
        id: 'image-system',
        name: 'Image System',
        description: 'Robust image primitives with failsafe fallbacks and standardized aspect ratios.',
        category: 'styles',
        tags: ['new'],
        component: dynamic(() => import('@/components/Style/image-showcase').then(mod => mod.ImageShowcase)),
        sourceCodePath: 'components/Media/image-showcase.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'stats-section-1',
        name: 'Stats-Section-1',
        description: 'A clean 3-column grid for displaying company statistics and neural response times.',
        category: 'stats',
        tags: ['new'],
        component: dynamic(() => import('@/components/Stats/stats-section-1').then(mod => mod.StatsSection1)),
        sourceCodePath: 'components/Stats/stats-section-1.tsx',
        dependencies: ['lucide-react', 'clsx'],
    },
    {
        id: 'stats-section-2',
        name: 'Stats-Section-2',
        description: 'Scroll-linked velocity text using framer-motion.',
        category: 'stats',
        tags: ['new'],
        component: dynamic(() => import('@/components/Stats/stats-section-2').then(mod => mod.StatsSection2)),
        sourceCodePath: 'components/Stats/stats-section-2.tsx',
        dependencies: ['framer-motion', 'clsx'],
    },
    {
        id: 'stats-section-3',
        name: 'Stats-Section-3',
        description: 'Bento-style metrics grid featuring animated SVG gradient backgrounds and Framer Motion view stagger.',
        category: 'stats',
        tags: ['new'],
        component: dynamic(() => import('@/components/Stats/stats-section-3').then(mod => mod.StatsSection3)),
        sourceCodePath: 'components/Stats/stats-section-3.tsx',
        dependencies: ['framer-motion', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'stats-section-4',
        name: 'Stats-Section-4',
        description: 'A clean, high-impact stats section featuring large metric typography and a detailed feature grid.',
        category: 'stats',
        tags: ['new'],
        component: dynamic(() => import('@/components/Stats/stats-section-4').then(mod => mod.StatsSection4)),
        sourceCodePath: 'components/Stats/stats-section-4.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'stats-section-5',
        name: 'Stats-Section-5',
        description: 'Sophisticated metric cards with colorful side-accents and bold typography for high-impact growth data.',
        category: 'stats',
        tags: ['new'],
        component: dynamic(() => import('@/components/Stats/stats-section-5').then(mod => mod.StatsSection5)),
        sourceCodePath: 'components/Stats/stats-section-5.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge', 'framer-motion'],
    },

    {
        id: 'login-1',
        name: 'Login-1',
        description: 'Clean modern login form with social authentication and validation.',
        category: 'form',
        tags: ['new'],
        component: dynamic(() => import('@/components/Form/login-1')),
        sourceCodePath: 'components/Form/login-1.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'contact-1',
        name: 'Contact-1',
        description: 'Clean modern contact form with responsive grid layout.',
        category: 'form',
        tags: ['new'],
        component: dynamic(() => import('@/components/Form/contact-us-1')),
        sourceCodePath: 'components/Form/contact-us-1.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'contact-2',
        name: 'Contact-2',
        description: 'Split layout contact form with a large visual showcase side.',
        category: 'form',
        tags: ['new'],
        component: dynamic(() => import('@/components/Form/contact-us-2')),
        sourceCodePath: 'components/Form/contact-us-2.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'contact-3',
        name: 'Contact-3',
        description: 'Split layout contact form with info icons on the left and form on the right.',
        category: 'form',
        tags: ['new'],
        component: dynamic(() => import('@/components/Form/contact-us-3')),
        sourceCodePath: 'components/Form/contact-us-3.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'blog-1',
        name: 'Blog-1',
        description: 'Modern blog section with featured posts grid and header actions.',
        category: 'blog',
        tags: ['new'],
        component: dynamic(() => import('@/components/Blog/blog-1').then(mod => mod.BlogSection)),
        sourceCodePath: 'components/Blog/blog-1.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'blog-2',
        name: 'Blog-2',
        description: 'Vertical list of blog posts with side-aligned images and category badges.',
        category: 'blog',
        tags: ['new'],
        component: dynamic(() => import('@/components/Blog/blog-2').then(mod => mod.BlogSection)),
        sourceCodePath: 'components/Blog/blog-2.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'blog-3',
        name: 'Blog-3',
        description: '3-column blog card grid with featured images, excerpts, and reading actions.',
        category: 'blog',
        tags: ['new'],
        component: dynamic(() => import('@/components/Blog/blog-3').then(mod => mod.BlogSection)),
        sourceCodePath: 'components/Blog/blog-3.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'blog-4',
        name: 'Blog-4',
        description: 'Large featured post layout with a vertical sidebar list and tab-based filtering.',
        category: 'blog',
        tags: ['new'],
        component: dynamic(() => import('@/components/Blog/blog-4').then(mod => mod.BlogSection)),
        sourceCodePath: 'components/Blog/blog-4.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'sponsor-1',
        name: 'Classic Sponsor Grid',
        description: 'A clean grid of sponsor logos with interactive hover effects and border separation.',
        category: 'sponsor',
        tags: ['new'],
        component: dynamic(() => import('@/components/Sponsor/sponsor-1').then(mod => mod.SponsorSection)),
        sourceCodePath: 'components/Sponsor/sponsor-1.tsx',
        dependencies: ['lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'card-parallax-1',
        name: 'Stacked Parallax Cards',
        description: 'A smooth, scroll-linked stacked card effect with scale and parallax visual transitions.',
        category: 'parallax',
        tags: ['new'],
        component: dynamic(() => import('@/components/Parallax/card-effect-1').then(mod => mod.CardParallax)),
        sourceCodePath: 'components/Parallax/card-effect-1.tsx',
        dependencies: ['framer-motion', 'lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'card-parallax-2',
        name: 'Full Stack Parallax',
        description: 'Clean, Basebox-styled card stacking effect where one card covers the other completely.',
        category: 'parallax',
        tags: ['new', 'pro'],
        component: dynamic(() => import('@/components/Parallax/card-effect-2').then(mod => mod.CardStackParallax)),
        sourceCodePath: 'components/Parallax/card-effect-2.tsx',
        dependencies: ['framer-motion', 'lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'parallax-scroll-1',
        name: 'Multi-Column Gallery',
        description: 'A smooth, multi-column parallax scrolling gallery with staggered vertical motion.',
        category: 'parallax',
        tags: ['new'],
        component: dynamic(() => import('@/components/Parallax/scroll-1').then(mod => mod.SmoothParallaxScroll)),
        sourceCodePath: 'components/Parallax/scroll-1.tsx',
        dependencies: ['framer-motion', 'lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'text-scroll-1',
        name: 'Text Scroll Parallax',
        description: 'Large bold typography and images moving horizontally on scroll.',
        category: 'parallax',
        tags: ['new'],
        component: dynamic(() => import('@/components/Parallax/text-scroll-1').then(mod => mod.TextParallaxScroll)),
        sourceCodePath: 'components/Parallax/text-scroll-1.tsx',
        dependencies: ['framer-motion', 'lucide-react', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'text-1',
        name: 'Highlighter',
        description: 'Text that uses a hand-drawn marker effect for emphasis.',
        category: 'text',
        tags: ['new'],
        component: dynamic(() => import('@/components/Text/text-1').then(mod => mod.Text1)),
        sourceCodePath: 'components/Text/text-1.tsx',
        dependencies: ['framer-motion', 'rough-notation', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'text-2',
        name: 'Kinetic Gradient',
        description: 'An animated gradient foreground text component using Framer Motion with optional border loops.',
        category: 'text',
        tags: ['new'],
        component: dynamic(() => import('@/components/Text/text-2').then(mod => mod.Text2)),
        sourceCodePath: 'components/Text/text-2.tsx',
        dependencies: ['framer-motion', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'text-3',
        name: 'Performance CountUp',
        description: 'A high-performance number animation component using spring physics and direct DOM manipulation.',
        category: 'text',
        tags: ['new'],
        component: dynamic(() => import('@/components/Text/text-3').then(mod => mod.Text3)),
        sourceCodePath: 'components/Text/text-3.tsx',
        dependencies: ['framer-motion', 'clsx', 'tailwind-merge'],
    },
    {
        id: 'text-4',
        name: 'Hyper Scramble Text',
        description: 'A tech-focused text reveal component that scrambles random characters before resolving to the target string.',
        category: 'text',
        tags: ['new', 'pro'],
        component: dynamic(() => import('@/components/Text/text-4').then(mod => mod.Text4)),
        sourceCodePath: 'components/Text/text-4.tsx',
        dependencies: ['framer-motion', 'clsx', 'tailwind-merge'],
    }
];